const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium,devices}=require('playwright');
const file=path.join(__dirname,'../index.html'),legacy=process.env.NATIONS_LEGACY_HTML,output=process.env.TEST_OUTPUT_DIR,server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(fs.readFileSync(req.url==='/legacy'&&legacy?legacy:file));});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH});const errors=[];try{for(const device of [{name:'desktop',viewport:{width:1440,height:1000}},{...devices['Pixel 7'],name:'mobile'}]){
 const context=await browser.newContext(device),page=await context.newPage();page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.stack));const url='http://127.0.0.1:'+server.address().port;await page.goto(url+(legacy?'/legacy':''));await page.waitForSelector('#profile-form');
 const original=await page.evaluate(async()=>{state=Core.createCareer(DB,{...Core.clone(DB.profile.defaults),name:'네이션스 UI 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0');screen='dashboard';await persist(true);render();return {club:state.player.club,contract:Core.clone(state.player.contract),history:Core.clone(state.player.history),fixtures:Core.clone(state.fixtures)};});
 if(legacy){await page.goto(url);await page.waitForFunction(()=>!storageLoading&&state?.nations);assert.deepEqual(await page.evaluate(()=>({club:state.player.club,contract:state.player.contract,history:state.player.history,fixtures:state.fixtures})),original);}
 await page.evaluate(()=>{screen='nations';render();});assert.equal(await page.locator('#national-team option').count(),114);assert.equal(await page.locator('.national-kits .shirt').count(),2);assert.match(await page.locator('.national-hero').innerText(),/대한민국/);
 await page.selectOption('#national-team','nt-br');assert.match(await page.locator('.national-hero').innerText(),/브라질/);assert.match(await page.locator('.national-kits .shirt').first().getAttribute('style'),/#FFDF00/);await page.selectOption('#national-team','nt-kr');
 if(output){fs.mkdirSync(output,{recursive:true});await page.screenshot({path:path.join(output,device.name+'-national-overview.png'),fullPage:true});}
 await page.evaluate(()=>{const p=state.player;for(const a of DB.attributes)p.stats[a.id]=95;p.trust=100;p.fitness=100;while(p.history.length<5){p.injury=0;p.injuryDays=0;p.fitness=100;Core.advance(DB,state);}p.injury=0;p.injuryDays=0;p.fitness=100;state.nations.trust=95;const event={id:'ui-national-camp',from:state.date,until:Core.dateAdd(state.date,10),matchDates:[Core.dateAdd(state.date,4),Core.dateAdd(state.date,8)],window:'ui'};Core.processNationalCamp(DB,state,event);if(!state.nations.camp)throw Error('Player was not called up: '+JSON.stringify(Core.nationalAssessment(DB,state)));screen='nations';render();});
 assert.match(await page.locator('.national-overview').innerText(),/대표팀 소집/);assert.equal(await page.locator('.content[data-screen="nations"] tr.highlight').count()>=1,true);
 for(const scale of [100,200]){await page.evaluate(scale=>{preferences.scale=scale;render();},scale);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,device.name+' national UI overflow at '+scale+'%');}
 await page.evaluate(()=>{preferences.scale=100;const fixture=Core.nationalOwnFixtures(state).find(f=>!f.result&&f.date>=state.date);state.date=fixture.date;const report=Core.playNationalDay(DB,state);if(!report)throw Error('No international report');validateSave(envelope());state.matchPresentation={reportId:report.id,phase:'lineup',cursor:0,paused:true};render();});
 assert.equal(await page.locator('.formation-card').count(),2);assert.match(await page.locator('.match-header').innerText(),/A매치/);if(output)await page.screenshot({path:path.join(output,device.name+'-national-lineups.png'),fullPage:true});
 const expected=await page.evaluate(async()=>{validateSave(envelope());await persist(true);return {nations:Core.clone(state.nations),club:state.player.club,contract:Core.clone(state.player.contract),report:state.matchPresentation.reportId};});await page.reload();await page.waitForFunction(()=>!storageLoading&&state?.matchPresentation);assert.deepEqual(await page.evaluate(()=>({nations:state.nations,club:state.player.club,contract:state.player.contract,report:state.matchPresentation.reportId})),expected);assert.equal(await page.locator('.formation-card').count(),2);
 await page.click('[data-action="match-locker"]');assert.equal(await page.locator('.locker-room').count(),1);await page.click('[data-action="match-start"]');await page.click('[data-action="match-skip"]');assert.match(await page.locator('.content').innerText(),/대한민국/);await page.evaluate(()=>{screen='nations';state.matchPresentation=null;render();});assert.match(await page.locator('.national-overview').innerText(),/A매치 출전/);
 await page.evaluate(()=>{state.date='2030-06-04';state.seasonStart='2029-08-01';Core.startNationalTournament(DB,state,{key:'world-cup:2030',competition:'world-cup',year:2030,start:'2030-06-11',date:state.date});nationalTeamSelection='nt-kr';nationalTournamentSelection='world-cup:2030';screen='nations';render();});assert.equal(await page.locator('.national-group').count(),12);if(output)await page.screenshot({path:path.join(output,device.name+'-world-cup-groups.png'),fullPage:true});
 await context.close();console.log(device.name+': legacy migration, 114 teams, kits, callup, 100/200% layout, A-match phases, save/reload and World Cup groups passed');
 }assert.deepEqual(errors,[]);console.log('Browser errors: 0');}finally{await browser.close();server.close();}})().catch(error=>{console.error(error);server.close();process.exitCode=1;});
