const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),engine=section('game-engine'),ui=section('game-ui'),ctx=vm.createContext({});vm.runInContext(engine+';globalThis.C=FootballCore;',ctx);const C=ctx.C,plain=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x)),profile={...C.clone(DB.profile.defaults),name:'생활 개선 검증',startingSeed:411,stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},base=C.createCareer(DB,profile,'domestic','kr2-0'),career=()=>C.clone(base);
const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast(')),imports=ui.slice(ui.indexOf('function prepareImportedCareer('),ui.indexOf('async function restoreCareer('));vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=key=>key;${validators}${imports};globalThis.V={validateDB,validateSave,prepareImportedCareer};`,ctx);
function uiFunction(name){const start=ui.indexOf('function '+name+'(');assert.ok(start>=0,name);const lines=ui.slice(start).split('\n');for(let i=1;i<=lines.length;i++){const code=lines.slice(0,i).join('\n');try{new vm.Script('('+code+'\n)');return code;}catch{}}throw Error('Unterminated function '+name);}
const h=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),t=(key,vars={})=>(DB.ui.labels[key]||key).replace(/\{(\w+)\}/g,(_,k)=>vars[k]??'');
function screen(s){const context=vm.createContext({DB,state:s,preferences:{currency:'KRW'},Core:C,h,t,n:(n,d=0)=>Number(n).toFixed(d),infoLabel:h,badge:()=>'',btn:(label,action,attrs='')=>'<button data-action="'+action+'" '+attrs+'>'+label+'</button>',detail:(label,value)=>'<div>'+h(label)+': '+h(value)+'</div>',financeHead:()=>'',financeButton:(label,operation,id,extra,disabled)=>'<button data-operation="'+operation+'" data-id="'+id+'" '+(disabled?'disabled':'')+'>'+label+'</button>',creationSteps:()=>'',crest:()=>'',clubTier:()=>'',idx:()=>C.indexes(DB),openModal:markup=>context.markup=markup});vm.runInContext(ui.split('\n').find(line=>line.startsWith('const displayMoney='))+'\nconst money=value=>h(displayMoney(value));',context);return context;}

test('20.9.1 configuration and scripts validate; all starting routes and alternatives obey KRW monthly bands and preserve sign/preview consistency',()=>{
 ctx.V.validateDB(DB);new vm.Script(engine);new vm.Script(ui);assert.equal(JSON.parse(fs.readFileSync(path.join(__dirname,'../version.json'),'utf8')).version,DB.meta.version);
 const offers=C.startingOffers(DB,profile),rate=DB.settings.currencies.find(c=>c.id==='KRW').rate;
 for(const offer of offers)for(const club of offer.alternatives){const rule=DB.startingRouteRules.initialContract[offer.route.id],weekly=C.initialWage(DB,club.id,profile,offer.route.id),monthly=weekly*DB.rules.annualSalaryWeeks/rule.monthsPerYear*rate;assert.ok(monthly>=rule.minimumMonthlyKRW&&monthly<=rule.maximumMonthlyKRW,offer.route.id+':'+club.id);}
 assert.equal(base.player.contract.weekly,C.initialWage(DB,base.player.club,profile,'domestic'));
 for(const id of ['europe','academy']){const offer=offers.find(o=>o.route.id===id),signed=C.createCareer(DB,profile,id,offer.alternatives[1].id);assert.equal(signed.player.contract.weekly,C.initialWage(DB,offer.alternatives[1].id,profile,id));}
 const s=screen(base);s.draft=C.clone(profile);s.Core={...C,startingOffers:()=>offers};vm.runInContext(uiFunction('showContracts'),s);s.showContracts();assert.ok(s.markup.includes('월 환산 급여'));for(const offer of offers){s.draft.startingClubSelections[offer.route.id]=offer.alternatives[1].id;}s.showContracts();for(const offer of offers){const club=offer.alternatives[1],w=C.initialWage(DB,club.id,profile,offer.route.id),amount=new Intl.NumberFormat(DB.meta.locale,{style:'currency',currency:'KRW',maximumFractionDigits:0}).format(w*rate);assert.ok(s.markup.includes(amount));assert.ok(s.markup.includes('data-club="'+club.id+'"'));}
});

test('value chart uses equally spaced evaluation categories for unequal dates and long careers, preserving exact dates and accessible record labels',()=>{
 const s=screen(base);vm.runInContext(uiFunction('playerValueChartLayout')+'\n'+uiFunction('playerValueHistoryCard'),s);
 for(const dates of [['2026-07-31','2026-08-01','2038-01-01','2038-08-01'],Array.from({length:30},(_,i)=>(2026+i)+'-08-01')]){const records=dates.map((date,i)=>({date,value:100000+i*100,kind:i?'periodic':'initial'})),layout=s.playerValueChartLayout(records,DB.valueHistoryRules.chart),gaps=layout.points.slice(1).map((point,i)=>point.x-layout.points[i].x);assert.ok(gaps.every(gap=>Math.abs(gap-gaps[0])<1e-8));s.state={...base,playerValueHistory:{records}};const markup=s.playerValueHistoryCard();assert.equal((markup.match(/class="chart-dot"/g)||[]).length,records.length);assert.ok(dates.every(date=>markup.includes(date)));if(records.length>10)assert.ok(layout.chartWidth>DB.valueHistoryRules.chart.width);}
 const one=s.playerValueChartLayout([{date:'2026-07-31',value:0}],DB.valueHistoryRules.chart);assert.ok(Number.isFinite(one.points[0].x)&&Number.isFinite(one.points[0].y));
});

test('vacation quote is a real live-updated element rather than escaped HTML and follows display currency',()=>{
 const s=screen(base),usd=value=>new Intl.NumberFormat(DB.meta.locale,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value*DB.settings.currencies.find(c=>c.id==='USD').rate);vm.runInContext(uiFunction('vacationView'),s);const markup=s.vacationView();assert.ok(markup.includes('<span id="vacation-quote" aria-live="polite">₩'));assert.ok(!markup.includes('&lt;span'));s.preferences.currency='USD';assert.ok(s.vacationView().includes('<span id="vacation-quote" aria-live="polite">'+h(usd(C.vacationQuote(DB,base,DB.vacationRules.destinations[0].id,7)))));
 const listeners={},target={textContent:''},form={elements:{destination:{value:DB.vacationRules.destinations[1].id},days:{value:'10'}}};s.document={addEventListener:(type,fn)=>listeners[type]=fn,getElementById:()=>target};vm.runInContext(ui.split('\n').find(line=>line.includes("const form=event.target.closest?.('#vacation-form')")),s);listeners.input({target:{closest:()=>form}});assert.equal(target.textContent,usd(C.vacationQuote(DB,base,form.elements.destination.value,10)));assert.ok(!target.textContent.includes('<span'));form.elements.days.value='0';listeners.input({target:{closest:()=>form}});assert.equal(target.textContent,'—');
});

test('personal services debit real cash, record periods, block unpaid/duplicate categories and stop effects after paid periods',()=>{
 const s=career();C.careerIncome(DB,s,3000,'salary');s.player.morale=70;const cash=s.economy.cash,stats=plain(s.player.stats),item=DB.economyRules.personalSpending.items.find(d=>d.id==='meal-plan');assert.equal(C.buyPersonalSpending(DB,s,item.id),true);assert.equal(s.economy.cash,cash-item.cost);assert.equal(s.economy.personalSpending.history.length,1);assert.equal(s.economy.ledger.at(-1).type,'personalSpending');assert.equal(s.economy.personalSpending.active[0].until,C.dateAdd(s.date,item.days));assert.equal(C.buyPersonalSpending(DB,s,'personal-chef'),false);assert.equal(C.buyPersonalSpending(DB,s,'meal-plan'),false);assert.equal(C.buyPersonalSpending(DB,s,'missing'),false);
 const neutral=C.personalSpendingEffects(DB,s),active=C.personalSpendingEffects(DB,s,C.dateAdd(s.date,1));assert.equal(neutral.recoveryDaily,0);assert.equal(active.recoveryDaily,item.recoveryDaily);assert.equal(C.personalSpendingEffects(DB,s,C.dateAdd(s.date,item.days)).recoveryDaily,item.recoveryDaily);assert.equal(C.personalSpendingEffects(DB,s,C.dateAdd(s.date,item.days+1)).recoveryDaily,0);
 assert.equal(C.buyPersonalSpending(DB,s,'family-evening'),true);assert.equal(s.player.morale,71.5);assert.deepEqual(plain(s.player.stats),stats);
 const poor=career();assert.equal(C.buyPersonalSpending(DB,poor,'meal-plan'),false);C.careerIncome(DB,poor,1000,'salary');poor.economy.arrears=1;assert.equal(C.buyPersonalSpending(DB,poor,'meal-plan'),false);const busy=career();C.careerIncome(DB,busy,1000,'salary');busy.matchPresentation={};assert.equal(C.buyPersonalSpending(DB,busy,'meal-plan'),false);
 const view=screen(s);vm.runInContext(uiFunction('personalSpendingCard'),view);const markup=view.personalSpendingCard();assert.ok(markup.includes('₩'));assert.ok(markup.includes(item.name));assert.ok(markup.includes('data-operation="personal-spending"'));assert.ok(markup.includes(s.economy.personalSpending.active[0].until));ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});
});

test('paid daily services affect real recovery, fatigue, morale and training injury risk within caps, without buying ability or continuing through vacation',()=>{
 const ordinary=career(),supported=career();for(const s of [ordinary,supported]){C.setPlayStyleBuild(DB,s,C.playStyleDefaults(DB));C.careerIncome(DB,s,4000,'salary');s.player.fitness=60;s.player.morale=60;s.trainingProgram.fatigue=30;}
 for(const id of ['personal-chef','recovery-team','mental-coaching','daily-support','fitted-boots'])assert.equal(C.buyPersonalSpending(DB,supported,id),true);
 const effects=C.personalSpendingEffects(DB,supported,C.dateAdd(supported.date,1)),limits=DB.economyRules.personalSpending.limits;assert.equal(effects.recoveryDaily,limits.recoveryDaily);assert.equal(effects.fatigueDaily,limits.fatigueDaily);assert.ok(effects.moraleDaily<=limits.moraleDaily&&effects.injuryFactor>=limits.minimumInjuryFactor);
 for(const s of [ordinary,supported]){s.trainingProgram.plan.intensity='intensive';s.date=C.dateAdd(s.date,1);}const session={work:true,date:supported.date};assert.ok(C.trainingInjuryChance(DB,supported,session)<C.trainingInjuryChance(DB,ordinary,session));
 // Use the actual condition update from the engine with controlled sessions.
 const start=engine.indexOf('  function updateTrainingCondition('),end=engine.indexOf('  function trainingInjuryChance(',start);ctx.personalSpendingEffects=C.personalSpendingEffects;ctx.clamp=C.clamp;vm.runInContext(engine.slice(start,end)+';globalThis.updateCondition=updateTrainingCondition;',ctx);
 const stats=plain(supported.player.stats);for(const s of [ordinary,supported])ctx.updateCondition(DB,s,{work:true,date:s.date,kind:'development',recovery:0,load:3});assert.ok(supported.player.fitness>ordinary.player.fitness);assert.ok(supported.trainingProgram.fatigue<ordinary.trainingProgram.fatigue);assert.ok(supported.player.morale>ordinary.player.morale);assert.deepEqual(plain(supported.player.stats),stats);
 supported.player.fitness=ordinary.player.fitness=60;supported.trainingProgram.fatigue=ordinary.trainingProgram.fatigue=30;supported.player.morale=ordinary.player.morale=60;for(const s of [ordinary,supported])ctx.updateCondition(DB,s,{work:false,date:s.date,kind:'vacation',recovery:0,load:0});assert.equal(supported.player.fitness,ordinary.player.fitness);assert.equal(supported.trainingProgram.fatigue,ordinary.trainingProgram.fatigue);assert.equal(supported.player.morale,ordinary.player.morale);
});

test('fresh career requires style registration first; reading never answers it and confirming neutral build resolves it exactly once',()=>{
 const s=career(),message=s.inbox.find(m=>m.action==='play-style');assert.ok(message);assert.equal(C.pendingResponses(DB,s)[0].id,message.id);assert.equal(C.advance(DB,s),false);message.read=true;assert.ok(C.pendingResponses(DB,s).some(m=>m.id===message.id));C.initializeSystems(DB,s);assert.equal(s.inbox.filter(m=>m.action==='play-style').length,1);
 const view=screen(s);view.playStyleSummary=()=>'';view.playStyleChanges=()=>'';view.interfaceSymbol=()=>'';vm.runInContext(uiFunction('playStyleBuilder'),view);const markup=view.playStyleBuilder();assert.ok(markup.includes('class="play-style-editor" open'));assert.ok(!/id="play-style-apply" disabled/.test(markup));
 assert.equal(C.setPlayStyleBuild(DB,s,{identity:'missing',onBall:'balanced',offBall:'balanced'}),false);assert.equal(s.player.playStyleSetupComplete,false);assert.equal(C.setPlayStyleBuild(DB,s,C.playStyleDefaults(DB)),true);assert.equal(message.answered,true);assert.equal(s.player.playStyleSetupComplete,true);assert.ok(!C.pendingResponses(DB,s).some(m=>m.id===message.id));C.initializeSystems(DB,s);assert.equal(s.inbox.filter(m=>m.action==='play-style').length,1);
 const elements={'play-style-apply':{},'play-style-preview':{},'play-style-message':{}};view.document={getElementById:id=>elements[id]};view.FormData=class{constructor(){return Object.entries(C.playStyleDefaults(DB));}};vm.runInContext(uiFunction('refreshPlayStyleDraft'),view);view.refreshPlayStyleDraft({querySelectorAll:()=>[]});assert.equal(elements['play-style-apply'].disabled,true);view.state.player.playStyleSetupComplete=false;view.refreshPlayStyleDraft({querySelectorAll:()=>[]});assert.equal(elements['play-style-apply'].disabled,false);
});

test('official mail templates preserve data and rewrite bundled old messages while retaining custom text',()=>{
 for(const [key,old] of Object.entries(DB.communicationRules.previousLabels)){const variables=new Set([...old.matchAll(/\{(\w+)\}/g)].map(m=>m[1])),current=new Set([...DB.ui.labels[key].matchAll(/\{(\w+)\}/g)].map(m=>m[1]));assert.deepEqual([...variables].sort(),[...current].sort(),key);const values=Object.fromEntries([...variables].map(k=>[k,k==='season'?'2':k==='tactic'?'4-3-3':k==='position'?'ST':'검증_'+k])),before=old.replace(/\{(\w+)\}/g,(_,k)=>values[k]),after=DB.ui.labels[key].replace(/\{(\w+)\}/g,(_,k)=>values[k]);assert.equal(C.communicationText(DB,before),after,key);}
 assert.ok(!DB.ui.labels.mailCoachBody.includes('네가'));assert.ok(!DB.ui.labels.trainingInjuryBody.includes('추첨'));assert.equal(C.communicationText(DB,'사용자 지정 구단 메일입니다.'),'사용자 지정 구단 메일입니다.');assert.equal(C.communicationText(DB,'사용자 · 직접 · 작성'),'사용자 · 직접 · 작성');
});

test('consumption and required style state round-trip; 20.9.0 saves keep contracts, vacations and roles without a new mandatory setup; malformed spending fails',()=>{
 const s=career();C.careerIncome(DB,s,1000,'salary');C.buyPersonalSpending(DB,s,'meal-plan');const saved={schema:DB.meta.schema,db:DB,state:s};ctx.V.validateSave(saved);const loaded=ctx.V.prepareImportedCareer(saved);assert.equal(loaded.state.player.playStyleSetupComplete,false);assert.equal(C.pendingResponses(loaded.db,loaded.state).filter(m=>m.action==='play-style').length,1);assert.deepEqual(plain(loaded.state.economy.personalSpending),plain(s.economy.personalSpending));assert.equal(loaded.state.economy.cash,s.economy.cash);
 const old=C.clone(DB);old.meta.version='20.9.0';delete old.economyRules.personalSpending;delete old.economyRules.ledgerTypes.personalSpending;delete old.communicationRules;delete old.valueHistoryRules.chart.minimumPointSpacing;old.startingRouteRules.initialContract=C.clone(DB.startingRouteRules.contractUpgrade.previous);delete old.startingRouteRules.contractUpgrade;Object.assign(old.ui.labels,DB.communicationRules.previousLabels);
 const legacy=career();delete legacy.player.playStyleSetupComplete;delete legacy.economy.personalSpending;legacy.inbox=legacy.inbox.filter(m=>m.action!=='play-style');legacy.player.contract.weekly=9000;const coach=legacy.inbox.find(m=>m.reply==='coach');coach.body=DB.communicationRules.previousLabels.mailCoachBody.replace('{tactic}','4-3-3').replace('{position}','ST');const reloaded=ctx.V.prepareImportedCareer({schema:DB.meta.schema,db:old,state:legacy});assert.equal(reloaded.state.player.contract.weekly,9000);assert.equal(reloaded.state.player.secondaryPosition,legacy.player.secondaryPosition);assert.equal(reloaded.state.player.playStyleSetupComplete,true);assert.ok(!C.pendingResponses(reloaded.db,reloaded.state).some(m=>m.action==='play-style'));assert.deepEqual(plain(reloaded.state.vacations),plain(legacy.vacations));assert.ok(reloaded.state.inbox.find(m=>m.id===coach.id).body.includes('예상 역할은 ST'));assert.ok(reloaded.db.startingRouteRules.initialContract.academy);
 for(const mutate of [state=>state.economy.personalSpending.active[0].definition='missing',state=>state.economy.personalSpending.active[0].until='2026-02-30',state=>state.economy.personalSpending.history.push(C.clone(state.economy.personalSpending.history[0]))]){const bad=C.clone(s);mutate(bad);assert.throws(()=>ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:bad}));}
});
