const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>{const part=html.split('<script id="'+id+'"')[1];return part.slice(part.indexOf('>')+1,part.indexOf('</script>'));},DB=JSON.parse(section('game-db')),ctx=vm.createContext({});
vm.runInContext(section('game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,ui=section('game-ui'),validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast('));
vm.runInContext('const DEFAULT_DB='+JSON.stringify(DB)+',Core=FootballCore,t=k=>k;'+validators+';globalThis.V={validateDB,validateSave};',ctx);
const plain=x=>JSON.parse(JSON.stringify(x)),profile=()=>({...C.clone(DB.profile.defaults),name:'사건 검증 선수',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))});
let seed;const create=()=>C.clone(seed??=C.createCareer(DB,profile(),'domestic','kr2-0'));
const activate=(s,id)=>{const event={id:'decision:'+s.season+':'+(++s.careerStories.serial),template:id,date:s.date,type:'decision',priority:DB.careerDecisionRules.priority,completed:true};s.calendar.entries.push(event);return C.activateCareerDecision(DB,s,event);};
const record=(s,id,minutes,keys=0)=>({id,date:s.date,season:s.season,club:s.player.club,stats:{...C.createStats(DB),minutes,keyPasses:keys,passes:10,completed:8,rating:7}});
test('starting offers remain stable, distinct and diverse across careers while preserving route difficulty',()=>{
 const seen=Object.fromEntries(DB.routes.map(r=>[r.id,new Set()])),leagues=new Set();
 for(let seed=0;seed<100;seed++){const p={...profile(),startingSeed:seed},offers=C.startingOffers(DB,p);assert.equal(offers.length,3);assert.deepEqual(plain(offers),plain(C.startingOffers(DB,p)));
  for(const o of offers){assert.equal(o.alternatives.length,3);assert.equal(new Set(o.alternatives.map(c=>c.id)).size,3);seen[o.route.id].add(o.club.id);for(const c of o.alternatives){assert.ok(!c.historical);assert.ok(c.quality<=o.route.qualityMax);assert.ok(C.squadOverall(DB,c.id)-C.overall(DB,p.stats)<=DB.startingRouteRules.diversity.maximumSquadGap);if(o.route.id==='domestic')assert.equal(c.league,DB.countries.find(n=>n.id===p.country).league);if(o.route.id==='europe')leagues.add(c.league);if(o.route.id==='academy')assert.ok(DB.startingRouteRules.academyTiers.includes(C.indexes(DB).clubs[c.parent].prestigeTier));}}
 }
 for(const [route,ids]of Object.entries(seen))assert.ok(ids.size>=10,route+': '+ids.size);assert.equal(leagues.size,DB.startingRouteRules.europeLeagues.length);
});
test('unrelated playoffs are rejected on delivery and removed from old inboxes, while own league and ordinary mail survive',()=>{
 const s=create(),own=DB.postseasonRules.boundaries.find(r=>[r.upper,...r.lowers].includes(C.indexes(DB,s).clubs[s.player.club].league)),foreign=DB.postseasonRules.boundaries.find(r=>![r.upper,...r.lowers].includes(C.indexes(DB,s).clubs[s.player.club].league)),key=r=>'postseason-result:1:'+r.id;
 assert.ok(own&&foreign);assert.equal(C.postseasonMessageRelevant(DB,s,{key:key(own)}),true);assert.equal(C.postseasonMessageRelevant(DB,s,{key:key(foreign)}),false);const before=s.inbox.length;
 C.mail(DB,s,{key:key(foreign),subject:'다른 나라',body:'플레이오프'});assert.equal(s.inbox.length,before);C.mail(DB,s,{key:key(own),subject:'내 리그',body:'플레이오프'});assert.equal(s.inbox.length,before+1);C.mail(DB,s,{key:'ordinary',subject:'일반',body:'내용'});assert.equal(s.inbox.length,before+2);
 const bad={...s.inbox.at(-1),id:'foreign-old',key:key(foreign)};s.inbox.push(bad);C.normalizeCareerSave(DB,s);assert.ok(!s.inbox.some(m=>m.id===bad.id));assert.ok(s.inbox.some(m=>m.key==='ordinary'));ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});
});
test('situational eligibility, topic cooldown and event-day revalidation stop irrelevant repeated events',()=>{
 const s=create(),t=id=>DB.careerDecisions.find(e=>e.id===id);
 assert.equal(C.careerTemplateEligible(DB,s,t('scene:injury')),false);s.player.injury=5;assert.equal(C.careerTemplateEligible(DB,s,t('scene:injury')),true);
 s.player.injury=0;s.careerStories.history.push({id:'past',date:s.date,template:'scene:language'});assert.equal(C.careerTemplateEligible(DB,s,t('scene:language')),false);s.careerStories.history[0].template=DB.careerDecisions.find(e=>e.id!=='scene:arrival'&&e.topic===t('scene:arrival').topic).id;assert.equal(C.careerTemplateEligible(DB,s,t('scene:arrival')),false);
 s.careerStories.history=[];const p=activate(s,'scene:injury');assert.notEqual(p.template,'scene:injury');assert.ok(Object.values(p.vars).every(v=>typeof v==='string'));assert.ok(!C.template(t(p.template).description,p.vars).includes('{coach}'));assert.equal(C.resolveCareerDecision(DB,s,'balanced').template,p.template);
 const future=s.calendar.entries.filter(e=>e.type==='decision'&&!e.completed);assert.equal(future.length,1);assert.ok(future[0].date>=C.dateAdd(s.date,18));assert.ok(future[0].date<=C.dateAdd(s.date,30));
});
test('episodes use actual club records, require minimum appearances and resolve a follow-up exactly once',()=>{
 const s=create();s.player.position='CM';activate(s,'scene:link');assert.ok(C.resolveCareerDecision(DB,s,'accept'));const e=s.careerStories.activeEpisode;assert.equal(e.chain,'link');assert.equal(C.careerEpisodeProgress(DB,s).matches,0);ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});
 const stats=JSON.stringify(s.player.stats);s.player.history.push(record(s,'first',90,5));assert.equal(C.careerEpisodeProgress(DB,s).achieved,false);s.player.history.push(record(s,'second',90,1));assert.equal(C.careerEpisodeProgress(DB,s).achieved,true);C.queueCareerDecision(DB,s);const follow=s.calendar.entries.find(r=>r.episode===e.id);assert.equal(follow.template,'scene:link-success');activateFollow(s,follow);assert.ok(C.resolveCareerDecision(DB,s,'balanced'));assert.equal(s.careerStories.activeEpisode,null);assert.equal(s.careerStories.episodes.at(-1).status,'success');assert.equal(C.resolveCareerDecision(DB,s,'balanced'),false);assert.equal(JSON.stringify(s.player.stats),stats);
});
function activateFollow(s,event){event.completed=true;C.activateCareerDecision(DB,s,event);}
test('injury or lack of appearances can end an episode; transfers close promises and invalidate queued reviews',()=>{
 const s=create();s.player.position='CM';activate(s,'scene:link');C.resolveCareerDecision(DB,s,'balanced');const id=s.careerStories.activeEpisode.id;assert.ok(id);s.date=s.careerStories.activeEpisode.until;C.queueCareerDecision(DB,s);const event=s.calendar.entries.find(e=>e.episode===id);assert.equal(event.template,'scene:link-failure');activateFollow(s,event);C.resolveCareerDecision(DB,s,'balanced');assert.equal(s.careerStories.episodes.at(-1).status,'failure');
 const moved=create();moved.player.position='CM';activate(moved,'scene:link');C.resolveCareerDecision(DB,moved,'accept');moved.date=moved.careerStories.activeEpisode.until;C.queueCareerDecision(DB,moved);const stale=moved.calendar.entries.find(e=>e.episode);activateFollow(moved,stale);moved.player.club='kr2-1';C.queueCareerDecision(DB,moved);assert.equal(moved.careerStories.activeEpisode,null);assert.equal(moved.careerStories.pending,null);assert.equal(moved.careerStories.episodes.at(-1).status,'interrupted');assert.equal(stale.completed,true);
});
test('legacy content/save upgrade adds definitions without changing custom choices or decimal attributes; malformed references fail',()=>{
 const old=C.clone(DB);delete old.careerEventRules;delete old.careerEpisodes;delete old.postseasonInboxRules;delete old.startingRouteRules.diversity;delete old.ui.reviewGrowthDisplay;old.ui.labels.reviewGrowthHint=DB.ui.reworkLegacyLabels.reviewGrowthHint;old.careerDecisionRules.intervalMinDays=10;old.careerDecisionRules.intervalMaxDays=16;old.careerDecisions=old.careerDecisions.filter(t=>!t.id.startsWith('scene:'));old.careerDecisions[0].description='사용자 변경';for(const t of old.careerDecisions)for(const k of ['topic','kind','weight','requirements'])delete t[k];C.upgradeDatabase(DB,old);assert.equal(old.careerDecisionRules.intervalMinDays,18);assert.equal(old.ui.labels.reviewGrowthHint,DB.ui.labels.reviewGrowthHint);assert.equal(old.careerDecisions.length,47);assert.equal(old.careerDecisions[0].description,'사용자 변경');ctx.V.validateDB(old);
 const s=create();delete s.careerStories.episodes;delete s.careerStories.activeEpisode;delete s.careerStories.episodeSerial;delete s.careerStories.eventRevision;delete s.careerStories.nextCheckDate;const original=JSON.stringify(s.player.stats);C.normalizeCareerSave(DB,s);ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});assert.equal(JSON.stringify(s.player.stats),original);
 s.player.position='CM';activate(s,'scene:link');C.resolveCareerDecision(DB,s,'accept');ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});const bad=C.clone(s);bad.careerStories.activeEpisode.chain='missing';assert.throws(()=>ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:bad}),/careerEpisodes/);
});
test('season growth keeps decimals but compares to the preceding closing attributes when available',()=>{
 const s=create(),before=C.clone(s.player.stats);s.player.stats.speed+=2.6;s.player.stats.passing-=1.2;const first=C.captureSeasonReview(DB,s,true);assert.equal(first.growthBasis,'season-start');assert.ok(Math.abs(first.growth.speed-2.6)<1e-8);assert.equal(first.attributes.speed,s.player.stats.speed);
 s.season=2;s.seasonBaseline={season:2,date:s.date,stats:C.clone(s.player.stats),earned:s.player.earned};s.player.stats.speed+=.6;s.player.stats.passing+=.2;const second=C.captureSeasonReview(DB,s,true);assert.equal(second.growthBasis,'previous-season');assert.ok(Math.abs(second.growth.speed-.6)<1e-8);assert.ok(Math.abs(second.growth.passing-.2)<1e-8);assert.ok(Math.abs(s.player.stats.speed-before.speed-3.2)<1e-8);
});