const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ui=section('game-ui');
const ctx=vm.createContext({});vm.runInContext(section('game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C;
const career=()=>C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'주장 자격 확인',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0'),plain=value=>JSON.parse(JSON.stringify(value));
function veteran(s){const p=s.player;p.age=30;p.trust=100;p.reputation=100;p.personality='disciplined';p.traits.professionalism=90;p.traits.mental=90;p.career[0].date=C.dateAdd(s.date,-DB.captainRules.tenureDays);for(const a of DB.attributes)p.stats[a.id]=95;p.captainHistory=[{club:p.club,date:s.date,season:1,rank:1}];return p;}

test('all executable scripts parse and the update manifest agrees with the database',()=>{new vm.Script(section('game-engine'));new vm.Script(ui);assert.equal(JSON.parse(fs.readFileSync(path.join(__dirname,'../version.json'),'utf8')).version,DB.meta.version);});
test('star power and former captain status cannot bypass age, continuous tenure, personality or character',()=>{
 const s=career();veteran(s);const club=s.player.club,candidate=()=>C.captainCandidates(DB,s,club).find(p=>p.id==='player');assert.equal(candidate().eligible,true);
 for(const mutate of [p=>p.age=DB.captainRules.minimumAge-1,p=>p.career[0].date=C.dateAdd(s.date,-DB.captainRules.tenureDays+1),p=>p.personality='free',p=>p.traits.professionalism=DB.captainRules.minimumProfessionalism-1,p=>p.traits.mental=DB.captainRules.minimumMental-1,p=>p.trust=DB.captainRules.minimumTrust-1,p=>p.careerTraits=[{id:'hothead'}],p=>p.careerTraits=[{id:'lazy'}]]){veteran(s);s.player.careerTraits=[];mutate(s.player);assert.equal(candidate().eligible,false);assert.ok(!C.captainHierarchy(DB,s,club,true).includes('player'));}
 veteran(s);s.player.careerTraits=[];s.player.age=DB.captainRules.minimumAge;s.player.trust=DB.captainRules.minimumTrust;s.player.traits.professionalism=DB.captainRules.minimumProfessionalism;s.player.traits.mental=DB.captainRules.minimumMental;assert.equal(candidate().eligible,true);
 s.player.career.push({club,date:s.date,type:'promoted',season:1});assert.equal(candidate().eligible,false);
});
test('vacancies do not create appointments, registration keeps its schedule and an acting captain favors maturity over ability',()=>{
 const s=career(),club=s.player.club;for(const p of [...s.world.rosters[club],s.player])p.age=18;assert.deepEqual(plain(C.captainHierarchy(DB,s,club,true)),[null,null,null]);assert.equal(s.player.captainHistory.length,0);
 const player=veteran(s),order=C.captainHierarchy(DB,s,club,true);assert.equal(order[0],'player');player.age=18;assert.deepEqual(plain(C.captainHierarchy(DB,s,club)),plain(order));assert.ok(!C.captainHierarchy(DB,s,club,true).includes('player'));
 const peer=s.world.rosters[club][0];Object.assign(peer,{age:30,personality:'reserved',traits:{...peer.traits,professionalism:90,mental:90}});const team={club,captainOrder:[null,null,null],players:[{id:'player',stats:player.stats,entryMinute:1,exitMinute:90},{id:peer.id,stats:peer.stats,entryMinute:1,exitMinute:90}],redIds:[]};assert.equal(C.matchCaptain(DB,s,team),peer.id);assert.equal(player.captainHistory.length,1);
});
test('initial NPC service is bounded by age, while newly joined players remain ineligible',()=>{
 const s=career();for(const p of s.world.rosters[s.player.club]){const days=Math.round((Date.parse(s.date)-Date.parse(p.joinedDate))/DB.dynamics.secondsPerDay);assert.ok(days>=0&&days<=DB.captainRules.initialTenureMaxDays);assert.ok(days<=Math.max(0,p.age-DB.captainRules.initialJoiningAge)*DB.calendarRules.seasonDays);}assert.ok(!C.captainHierarchy(DB,s,s.player.club,true).includes('player'));
});

const listeners={},elements={'setting-scale-value':{textContent:''},'setting-scale-apply':{disabled:true}},storage=new Map(),document={addEventListener:(type,fn)=>(listeners[type]??=[]).push(fn),getElementById:id=>elements[id],documentElement:{style:{setProperty(){}}},body:{style:{zoom:'1'}}},localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};
const displayCtx=vm.createContext({document,localStorage});
const utilities=ui.slice(ui.indexOf('const h=value=>'),ui.indexOf('const idx=')),start=ui.indexOf('let preferences='),preferencesCode=ui.slice(start,ui.indexOf('loadPreferences();',start)+'loadPreferences();'.length),theme=ui.match(/function applyTheme\(\)\{[^\n]+/)[0];
vm.runInContext(`const DB=${JSON.stringify(DB)},DEFAULT_DB=DB,Core={clamp:(v,min,max)=>Math.max(min,Math.min(max,v))};const options=()=>'',btn=()=>'',applyLayout=()=>{},positionUpdateNotice=()=>{};let renders=0;const toast=()=>{};function render(){renders++;applyTheme();}${utilities}${theme}${preferencesCode};globalThis.U={settings,displayCurrencyText,moneyText,money,prefs:()=>({...preferences}),pending:()=>pendingUiScale,setCurrency:id=>preferences.currency=id,renders:()=>renders};`,displayCtx);
const U=displayCtx.U,dispatch=(type,target)=>listeners[type].forEach(fn=>fn({target}));
test('scale input changes only the draft; currency rerenders preserve it; Apply writes and changes zoom once',()=>{
 dispatch('input',{id:'setting-scale',value:'140'});assert.equal(U.pending(),140);assert.equal(U.prefs().scale,100);assert.equal(document.body.style.zoom,'1');assert.equal(storage.size,0);assert.equal(elements['setting-scale-value'].textContent,'140%');assert.equal(elements['setting-scale-apply'].disabled,false);assert.match(U.settings(),/value="140"/);
 dispatch('change',{id:'setting-currency',value:'KRW'});assert.equal(U.pending(),140);assert.equal(U.prefs().scale,100);assert.equal(document.body.style.zoom,'1');assert.equal(JSON.parse(storage.get(DB.settings.storageKey)).scale,100);
 dispatch('click',{closest:()=>({dataset:{action:'settings-scale-apply'},disabled:false})});assert.equal(U.prefs().scale,140);assert.equal(U.pending(),null);assert.equal(document.body.style.zoom,'1.4');assert.equal(JSON.parse(storage.get(DB.settings.storageKey)).scale,140);assert.match(U.settings(),/data-action="settings-scale-apply" disabled/);
 dispatch('input',{id:'setting-scale',value:'150'});dispatch('click',{closest:()=>({dataset:{action:'settings-reset'},disabled:false})});assert.equal(U.pending(),null);assert.equal(U.prefs().scale,100);assert.equal(document.body.style.zoom,'1');
});
test('historical base-currency messages and news format every amount at display time without double conversion',()=>{
 const original='주급 €1,000 · 계약금 EUR 2,000 · 재정 3,000 EUR · 손실 -€100 · 소액 €12.50';
 for(const id of ['KRW','USD']){U.setCurrency(id);const result=U.displayCurrencyText(original);for(const value of [1000,2000,3000,-100,12.5])assert.ok(result.includes(U.money(value)),result);assert.ok(!/€|EUR/.test(result));assert.equal(U.displayCurrencyText(U.money(1000)),U.money(1000));assert.equal(U.displayCurrencyText('나이 25 · 평점 7.5 · 날짜 2026-10-07'),'나이 25 · 평점 7.5 · 날짜 2026-10-07');assert.ok(U.moneyText('<script>€100</script>').startsWith('&lt;script&gt;'));}
 U.setCurrency('EUR');assert.equal(U.displayCurrencyText(original),original);for(const field of ['selected.body','item.headline','item.body','item.sns','item.fans','item.press','e.text','entry.text'])assert.ok(ui.includes(`moneyText(${field})`));
});
test('saved stock colors and eligibility defaults upgrade while custom values and existing state survive',()=>{
 const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast(')),imports=ui.slice(ui.indexOf('function prepareImportedCareer('),ui.indexOf('async function restoreCareer('));vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=k=>k;${validators}${imports};globalThis.reload=prepareImportedCareer;`,ctx);
 const s=career(),snapshot=JSON.stringify(s),preserved=(old,next,path='state')=>{if(old&&typeof old==='object'){if(Array.isArray(old))assert.equal(next.length,old.length,path+'.length');for(const key of Object.keys(old))preserved(old[key],next[key],path+'.'+key);}else assert.equal(next,old,path);};
 for(const [version,palette] of [['20.8.7',DB.ui.themeUpgrade.previous],['20.8.8',DB.ui.themeUpgrade.previousVibrancy]]){const old=C.clone(DB);old.meta.version=version;old.ui.theme=C.clone(palette);old.ui.theme.accent='#123456';old.ui.labels.uiSizeHint=DB.ui.themeUpgrade.previousLabels.uiSizeHint;if(version==='20.8.7')delete old.ui.themeUpgrade;else delete old.ui.themeUpgrade.previousVibrancy;delete old.ui.symbols;for(const key of ['minimumProfessionalism','minimumMental','minimumTrust','minimumDiscipline','blockedTraits','initialJoiningAge','initialTenureMaxDays'])delete old.captainRules[key];const loaded=ctx.reload({schema:DB.meta.schema,db:old,state:s});assert.equal(loaded.db.ui.theme.accent,'#123456');for(const key of Object.keys(DB.ui.theme).filter(k=>k!=='accent'))assert.equal(loaded.db.ui.theme[key],DB.ui.theme[key],version+' theme '+key);assert.equal(loaded.db.ui.labels.uiSizeHint,DB.ui.labels.uiSizeHint);assert.equal(loaded.db.captainRules.minimumProfessionalism,DB.captainRules.minimumProfessionalism);preserved(s,loaded.state);assert.equal(JSON.stringify(s),snapshot);}
});
