const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const h=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>h.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ctx=vm.createContext({});vm.runInContext(section('game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C;
const create=()=>C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'시장·순위 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0');
function eligible(){const s=create();s.date=C.dateAdd(s.seasonStart,153);s.player.reputation=60;s.player.age=21;s.player.traits.potential=95;for(const key of DB.attributes.map(a=>a.id)){s.player.stats[key]=85;s.player.development.caps[key]=s.player.development.birth[key]=95;}for(let i=0;i<12;i++){const stats=C.createStats(DB);stats.minutes=90;stats.rating=7.4;s.player.history.push({date:C.dateAdd(s.date,-100+i*7),stats,appearance:'starter'});}return s;}
test('automatic approaches are spread across the window, capped and require repeat/elite eligibility',()=>{
  const s=eligible(),dates=[];for(let day=153;day<=183;day++){s.date=C.dateAdd(s.seasonStart,day);const before=s.offers.length;C.refreshOffers(DB,s);const added=s.offers.slice(before);assert.ok(added.length<=DB.scoutingRules.batchMax);for(const o of added){dates.push(o.createdDate);C.offerAction(DB,s,o.id,'decline');}}
  assert.ok(dates.length>0);assert.ok(dates.length<=DB.scoutingRules.windowMaxOffers);assert.ok(dates[0]>C.dateAdd(s.seasonStart,153));for(let i=1;i<dates.length;i++)assert.ok((Date.parse(dates[i])-Date.parse(dates[i-1]))/86400000>=DB.scoutingRules.reviewMinDays);
  s.date=C.dateAdd(s.seasonStart,184);const before=s.offers.length;C.refreshOffers(DB,s);assert.equal(s.offers.length,before);
  const strong=DB.clubs.find(c=>!c.historical&&!c.parent&&!c.statusLock&&c.quality>=DB.scoutingRules.strongQuality),candidate=eligible();candidate.world.clubs[strong.id].finance=DB.dynamics.financeMax;assert.ok(C.scoutingCandidate(DB,candidate,strong));candidate.automaticOfferHistory[strong.id]={date:C.dateAdd(candidate.date,-365)};assert.equal(C.scoutingCandidate(DB,candidate,strong),null);delete candidate.automaticOfferHistory[strong.id];candidate.player.history=[];assert.equal(C.scoutingCandidate(DB,candidate,strong),null);
});
test('read receipts do not settle required responses; deferral, waiting, closure and renewal choices do',()=>{
  const s=create(),coach=C.pendingResponses(DB,s)[0];assert.equal(coach.reply,'coach');coach.read=true;assert.equal(C.pendingResponses(DB,s).length,1);assert.ok(C.replyCoach(DB,s,coach.id,'accept'));assert.equal(C.pendingResponses(DB,s).length,0);
  s.player.freeAgent=true;C.refreshOffers(DB,s);for(let i=0;i<40&&!s.offers.length;i++){s.date=s.marketReview.date;C.refreshOffers(DB,s);}const o=s.offers[0];assert.ok(o);const m=C.pendingResponses(DB,s)[0];m.read=true;assert.ok(C.pendingResponses(DB,s).some(m=>m.offer===o.id));assert.ok(C.offerAction(DB,s,o.id,'defer'));assert.equal(C.pendingResponses(DB,s).length,0);
  const d=C.startDeal(DB,s,o.club);assert.ok(d);assert.equal(C.pendingResponses(DB,s).length,1);d.awaiting=true;assert.equal(C.pendingResponses(DB,s).length,0);d.awaiting=false;d.status='ready';assert.equal(C.pendingResponses(DB,s).length,1);d.status='withdrawn';C.syncMarketState(DB,s);assert.equal(C.pendingResponses(DB,s).length,0);
  const renewal=create();for(const m of renewal.inbox)m.answered=true;renewal.player.contract.expiresSeason=2;renewal.date=C.dateAdd(renewal.seasonStart,300);C.renewalInvitation(DB,renewal);const request=C.pendingResponses(DB,renewal)[0];assert.equal(request.action,'renewal');request.answered=true;C.renewalInvitation(DB,renewal);assert.equal(C.pendingResponses(DB,renewal).length,0);assert.equal(renewal.inbox.filter(m=>m.action==='renewal').length,1);
});
test('each league leaderboard matches played team goals and assists, persists and isolates competitions',()=>{
  const s=create();while(s.date<C.dateAdd(s.seasonStart,15))C.advance(DB,s);const copy=C.normalizeCareerSave(DB,C.clone(s));
  for(const league of DB.leagues){const games=s.fixtures[league.id].filter(f=>f.result),rows=Object.values(s.competitionStats.leagues[league.id]||{});for(const key of ['goals','assists']){const expected=games.reduce((total,f)=>total+f.result.home.stats[key]+f.result.away.stats[key],0);assert.equal(rows.reduce((total,r)=>total+r[key],0),expected,league.id+' '+key);assert.equal(JSON.stringify(C.leaders(DB,copy,league.id,key)),JSON.stringify(C.leaders(DB,s,league.id,key)));}}
  assert.ok(C.leaders(DB,s,'en-1','goals').length);assert.ok(C.leaders(DB,s,'kr-2','assists').length);assert.equal(C.leaders(DB,s,'ucl','goals').length,0);
  const old=C.clone(s);delete old.competitionStats;C.normalizeCareerSave(DB,old,true);assert.ok(old.competitionStats.partial);assert.equal(old.competitionStats.startDate,old.date);assert.equal(C.leaders(DB,old,'kr-2','goals').length,0);
});
