const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ctx=vm.createContext({});
vm.runInContext(section('game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,ui=section('game-ui');
const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast('));
vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=k=>k;${validators};globalThis.V={validateDB,validateSave};`,ctx);
let base;function create(){base??=C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'네이션스 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0');return C.clone(base);}
const plain=v=>JSON.parse(JSON.stringify(v));
test('national teams cannot enter club scouting or transfer negotiations',()=>{const s=create(),team=C.indexes(DB,s).clubs['nt-kr'];assert.equal(C.scoutingCandidate(DB,s,team),null);assert.equal(C.contactAssessment(DB,s,team.id),null);assert.equal(C.agentContactIssue(DB,s,team.id),'contactUnavailable');assert.equal(C.startDeal(DB,s,team.id),null);});
function prove(s){for(const a of DB.attributes)s.player.stats[a.id]=95;for(let n=0;n<5;n++)s.player.history.push({id:'proof:'+n,date:C.dateAdd(s.date,-n-1),stats:{...C.createStats(DB),minutes:90,rating:7.8},club:s.player.club,appearance:'starter',season:s.season});s.player.fitness=100;s.nations.trust=90;}
function camp(s,key='test-camp'){const event={id:key,from:s.date,until:C.dateAdd(s.date,10),matchDates:[C.dateAdd(s.date,4),C.dateAdd(s.date,8)],window:key};C.processNationalCamp(DB,s,event);return event;}
function score(h,a){return {duration:90,home:{stats:{goals:h}},away:{stats:{goals:a}}};}
test('114 teams, representative kits and database references validate',()=>{const s=create();assert.equal(DB.nationalTeams.length,114);assert.equal(new Set(DB.nationalTeams.map(t=>t.country)).size,114);assert.equal(C.nationalTeam(DB,'KR').color,'#E32636');assert.equal(C.nationalTeam(DB,'BR').secondaryColor,'#009B3A');assert.ok(ctx.V.validateDB(DB));assert.ok(ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s}));for(const mutation of [d=>d.nationalTeams[0].color='red',d=>d.nationalRules.worldCupSlots.UEFA=15,d=>d.nationalTeams[0].tactic='missing']){const d=C.clone(DB);mutation(d);assert.throws(()=>ctx.V.validateDB(d));}});
test('callups depend on club proof, tactical evaluation, ability and availability',()=>{const s=create();assert.equal(C.nationalAssessment(DB,s).eligible,false);prove(s);assert.equal(C.nationalAssessment(DB,s).eligible,true);camp(s);assert.equal(C.nationalOnDuty(s),true);assert.equal(s.player.club,'kr2-0');assert.ok(s.nations.squads[s.nations.team].ids.includes('player'));for(const unavailable of ['injury','fitness']){const a=C.clone(s);if(unavailable==='injury')a.player.injury=1;else a.player.fitness=10;assert.equal(C.nationalAssessment(DB,a).eligible,false);}const frozen=C.clone(s.nations);C.initializeNations(DB,s);assert.deepEqual(plain(s.nations),plain(frozen));});
test('detailed international records, club ownership, bans and penalties remain separate',()=>{const s=create();prove(s);camp(s);const f=C.nationalOwnFixtures(s)[0],club=s.player.club,trust=s.player.trust,history=s.player.history.length,wage=s.player.contract.weekly;s.date=f.date;s.player.suspension=2;const report=C.playNationalDay(DB,s);assert.ok(report);assert.ok(report.result.preMatch);assert.equal(s.player.club,club);assert.equal(s.player.trust,trust);assert.equal(s.player.suspension,2);assert.equal(s.player.contract.weekly,wage);assert.equal(s.player.history.length,history);assert.equal(s.nations.history.length,1);const loaded=C.clone(s);assert.deepEqual(plain(C.nationalRecords(s).at(-1)),plain(C.nationalRecords(loaded).at(-1)));for(const side of ['home','away']){const t=report.result[side];assert.equal(t.stats.goals,t.players.reduce((n,p)=>n+p.match.goals,0));assert.equal(t.stats.assists,t.players.reduce((n,p)=>n+p.match.assists,0));assert.ok(t.stats.goals<=t.stats.onTarget&&t.stats.onTarget<=t.stats.shots);}const tied={...score(0,0)};C.resolveNationalPenalties(DB,s,{id:'test-final',home:f.home,away:f.away},tied);assert.notEqual(tied.penalties[0],tied.penalties[1]);assert.ok([f.home,f.away].includes(tied.winner));assert.equal(tied.home.stats.goals,0);});
test('48-team World Cup produces 12 groups, 32-team knockout and 104 matches including bronze',()=>{const s=create();s.date='2030-06-04';s.seasonStart='2029-08-01';C.startNationalTournament(DB,s,{key:'world-cup:2030',competition:'world-cup',year:2030,start:'2030-06-11',date:s.date});const t=s.nations.tournaments['world-cup:2030'];assert.equal(t.participants.length,48);assert.equal(t.groups.length,12);assert.equal(t.fixtures.length,72);for(const f of t.fixtures)f.result=score(1,0);s.date=t.fixtures.map(f=>f.date).sort().at(-1);C.advanceNationalTournament(DB,s,t);assert.equal(t.fixtures.filter(f=>f.stage==='round32').length,16);for(let pass=0;pass<8&&t.status!=='complete';pass++){const pending=t.fixtures.filter(f=>!f.result);for(const f of pending)f.result={...score(1,0),winner:f.home};s.date=pending.map(f=>f.date).sort().at(-1);C.advanceNationalTournament(DB,s,t);}assert.equal(t.status,'complete');assert.equal(t.fixtures.length,104);assert.equal(t.fixtures.filter(f=>f.stage==='third').length,1);assert.ok(t.champion);});
test('all confederation cups and Nations League reach finals with seeded groups',()=>{for(const competition of ['euro','asian-cup','afcon','copa-america','gold-cup','ofc-cup','uefa-nations','concacaf-nations']){const s=create(),c=DB.nationalCompetitions.find(c=>c.id===competition);s.seasonStart=c.firstYear+'-08-01';s.date=C.dateAdd(s.seasonStart,20);const key=competition+':'+c.firstYear;C.startNationalTournament(DB,s,{key,competition,year:c.firstYear,start:s.date,date:s.date});const t=s.nations.tournaments[key];assert.equal(t.participants.length,c.participants);for(let pass=0;pass<8&&t.status!=='complete';pass++){const pending=t.fixtures.filter(f=>!f.result);assert.ok(pending.length,competition);for(const f of pending)f.result={...score(1,0),...(f.decisive?{winner:f.home}:{})};s.date=pending.map(f=>f.date).sort().at(-1);C.advanceNationalTournament(DB,s,t);}assert.equal(t.status,'complete',competition);}});
test('migration adds only future national events and rejects damaged squad IDs',()=>{const s=create();delete s.nations;s.calendar.entries=s.calendar.entries.filter(e=>!e.type.startsWith('national'));C.advanceTrainingDays(DB,s,'2027-02-10',false);const original=plain(s.fixtures),history=plain(s.player.history);C.normalizeCareerSave(DB,s);assert.deepEqual(plain(s.fixtures),original);assert.deepEqual(plain(s.player.history),history);assert.ok(s.calendar.entries.filter(e=>e.type.startsWith('national')).every(e=>e.date>=s.date));assert.ok(ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s}));const damaged=C.clone(s);camp(damaged);damaged.nations.squads[damaged.nations.team].ids[0]='broken';assert.throws(()=>ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:damaged}));});
