const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ctx=vm.createContext({});vm.runInContext(section('game-engine')+';globalThis.Core=FootballCore;',ctx);const C=ctx.Core,ui=section('game-ui');vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)};const Core=FootballCore;const t=x=>x;${ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast('))};globalThis.validate={validateNpcMarketSave,validateNpcMarketDatabase};`,ctx);
const original=C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'AI 시장 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0'),create=()=>C.clone(original),cash=s=>Object.values(s.world.clubs).reduce((n,c)=>n+c.finance,0),plain=x=>JSON.parse(JSON.stringify(x));

test('summer and winter markets conserve fees, preserve identities and restrict turnover',()=>{
 const s=create(),money=cash(s),identities=new Set(Object.values(s.world.rosters).flat().map(p=>p.id)),before=new Map(Object.values(s.world.rosters).flat().map(p=>[p.id,plain({stats:p.stats,minutes:p.careerMinutes,seasonMinutes:p.seasonMinutes,country:p.country})]));
 for(let day=1;day<=DB.transferWindows.find(w=>w.id==='summer').end;day++){s.date=C.dateAdd(s.seasonStart,day);C.npcMarketDay(DB,s);}const m=s.world.npcMarket;assert.ok(m.serial>0,'AI players actually transfer');assert.ok(Math.abs(cash(s)-money)<.01,'fees debit buyers and credit sellers equally');
 const players=Object.values(s.world.rosters).flat();assert.equal(new Set(players.map(p=>p.id)).size,identities.size);for(const [club,list] of Object.entries(s.world.rosters)){assert.ok(list.length>=DB.npcMarketRules.minimumRoster&&list.length<=DB.npcMarketRules.maximumRoster);assert.ok(list.filter(p=>p.position==='GK').length>=DB.npcMarketRules.depthTargets.keeper);for(const p of list){assert.equal(p.club,club);assert.deepEqual(plain({stats:p.stats,minutes:p.careerMinutes,seasonMinutes:p.seasonMinutes,country:p.country}),before.get(p.id));}}
 for(const row of Object.values(m.clubs)){assert.ok(row.incoming<=3&&row.outgoing<=3&&row.coreSales<=DB.npcMarketRules.coreSales&&row.eliteDeals<=1);}ctx.validate.validateNpcMarketSave(DB,s);
 const frozen=m.serial;C.npcMarketDay(DB,s);assert.equal(m.serial,frozen,'same day is idempotent');s.date=C.dateAdd(s.seasonStart,70);C.npcMarketDay(DB,s);assert.equal(m.serial,frozen,'outside windows there are no deals');
 const w=DB.transferWindows.find(w=>w.id==='winter');for(let day=w.start;day<=w.end;day++){s.date=C.dateAdd(s.seasonStart,day);C.npcMarketDay(DB,s);}assert.ok(m.serial>frozen);for(const row of Object.values(m.clubs)){assert.ok(row.incoming<=4&&row.outgoing<=4);assert.ok((row.windows.winter?.incoming||0)<=1&&(row.windows.winter?.outgoing||0)<=1);}for(const p of players)assert.ok((p.transferHistory||[]).filter(t=>t.season===s.season).length<=1);assert.ok(Math.abs(cash(s)-money)<.01);ctx.validate.validateNpcMarketSave(DB,s);
});

test('financial distress, budget exhaustion and goalkeeper cover affect decisions',()=>{
 const s=create(),club='kr2-0',list=s.world.rosters[club],p=list.slice().sort((a,b)=>C.suitability(DB,a)-C.suitability(DB,b)).find(p=>p.position!=='GK');const normal=C.npcSaleAssessment(DB,s,p);assert.ok(normal);s.world.clubs[club].finance=s.world.npcMarket.clubs[club].openingFinance*.1;const distressed=C.npcSaleAssessment(DB,s,p);assert.equal(distressed.reason,'npcReasonFinance');assert.ok(distressed.fee<normal.fee);const target=Object.keys(s.world.npcMarket.clubs).find(id=>id!==club&&C.npcBuyerAssessment(DB,s,id,distressed));assert.ok(target);s.world.clubs[target].finance=0;assert.equal(C.npcBuyerAssessment(DB,s,target,distressed),null);
 const keepers=list.filter(p=>p.position==='GK');while(list.filter(p=>p.position==='GK').length>DB.npcMarketRules.depthTargets.keeper)list.splice(list.indexOf(list.find(q=>q.position==='GK')),1);for(const keeper of list.filter(p=>p.position==='GK'))assert.equal(C.npcSaleAssessment(DB,s,keeper),null);assert.ok(keepers.length>=2);
});

test('old careers gain market state without changing records; inflation is bounded',()=>{
 const s=create();delete s.world.npcMarket;const records=JSON.stringify({player:s.player,fixtures:s.fixtures});C.normalizeCareerSave(DB,s);assert.equal(JSON.stringify({player:s.player,fixtures:s.fixtures}),records);assert.equal(s.world.npcMarket.baseSeason,s.season);ctx.validate.validateNpcMarketSave(DB,s);
 const value=C.marketValue(DB,s.player,s),npc=s.world.rosters['kr2-0'][0],npcValue=C.npcMarketValue(DB,s,npc);s.season++;C.initializeNpcMarket(DB,s);assert.ok(Math.abs(C.marketValue(DB,s.player,s)/value-1.025)<.001);assert.ok(Math.abs(C.npcMarketValue(DB,s,npc)/npcValue-1.025)<.001);s.season=100;C.initializeNpcMarket(DB,s);assert.ok(C.marketValue(DB,s.player,s)<=Math.ceil(value*DB.npcMarketRules.maximumInflation));
 const bad=C.clone(DB);bad.npcMarketRules.summer.chance=2;assert.throws(()=>ctx.validate.validateNpcMarketDatabase(bad),/npcMarket/);
});
