const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=(source,id)=>source.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section(html,'game-db')),ui=section(html,'game-ui'),ctx=vm.createContext({});
vm.runInContext(section(html,'game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,plain=x=>JSON.parse(JSON.stringify(x));
const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast(')),imports=ui.slice(ui.indexOf('function prepareImportedCareer('),ui.indexOf('async function restoreCareer('));
vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=key=>key;${validators}${imports};globalThis.V={validateDB,validateSave,prepareImportedCareer};`,ctx);
let initial;function career(){initial??=C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'빌드 검증 선수',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,60]))},'domestic','kr2-0');return C.clone(initial);}
const offensive={identity:'finisher',onBall:'carry-first',offBall:'run'},defensive={identity:'winner',onBall:'one-touch',offBall:'cover'};

test('scripts parse, release versions agree and the renamed locker choice is in the editable database',()=>{
 new vm.Script(section(html,'game-engine'));new vm.Script(ui);assert.equal(DB.meta.version,JSON.parse(fs.readFileSync(path.join(__dirname,'../version.json'),'utf8')).version);assert.equal(DB.matchIntentRules.options.find(option=>option.id==='bold').name,'과감한 플레이를 자주 시도한다');ctx.V.validateDB(C.clone(DB));
});

test('all slot combinations respect caps and tradeoffs; position restrictions and invalid selections are enforced',()=>{
 const defaults=C.playStyleDefaults(DB);assert.deepEqual(plain(defaults),{identity:'balanced',onBall:'balanced',offBall:'balanced'});const neutral=C.playStyleEffects(DB,defaults);assert.ok([...Object.values(neutral.opportunity),...Object.values(neutral.execution),neutral.load].every(value=>value===1));assert.equal(neutral.longPassShare,0);assert.equal(neutral.passAccuracyDelta,0);
 for(const identity of DB.playStyleRules.slots[0].options)for(const onBall of DB.playStyleRules.slots[1].options)for(const offBall of DB.playStyleRules.slots[2].options){const build={identity:identity.id,onBall:onBall.id,offBall:offBall.id},effects=C.playStyleEffects(DB,build,'GK'),limits=DB.playStyleRules.limits;assert.equal(C.validPlayStyleBuild(DB,build,'GK'),true);for(const [category,values] of [['opportunity',effects.opportunity],['execution',effects.execution]])for(const value of Object.values(values))assert.ok(Number.isFinite(value)&&value>=limits[category+'Min']&&value<=limits[category+'Max']);assert.ok(effects.load>=limits.loadMin&&effects.load<=limits.loadMax);}
 assert.equal(C.validPlayStyleBuild(DB,{...defaults,identity:'sweeper'},'ST'),false);assert.equal(C.validPlayStyleBuild(DB,{...defaults,identity:'sweeper'},'GK'),true);assert.equal(C.playStyleEffects(DB,{...defaults,identity:'sweeper'},'ST').choices[0].active,false);
 for(const build of [null,[],{identity:'finisher'}, {...defaults,onBall:'unknown'},{...defaults,extra:'balanced'}])assert.equal(C.validPlayStyleBuild(DB,build),false);
 const offense=C.playStyleEffects(DB,offensive),defense=C.playStyleEffects(DB,defensive);assert.ok(offense.opportunity.shotWeight>1&&offense.opportunity.passWeight<1&&offense.load>1);assert.ok(defense.opportunity.defenseWeight>1&&defense.opportunity.shotWeight<1);assert.equal(C.playStyleOpportunity(offense,{id:'npc'},'shotWeight'),1);
});

test('neutral and legacy builds produce identical play; selected builds affect actual execution and preserve immutable match snapshots',()=>{
 const s=career(),fixture=Object.values(s.fixtures).flat().find(f=>[f.home,f.away].includes(s.player.club));s.player.trust=100;s.player.reputation=100;
 const legacyState=C.clone(s);delete legacyState.player.playStyleBuild;
 const before=JSON.stringify(s.player.stats),neutral=C.simulate(DB,fixture,s),legacy=C.simulate(DB,fixture,legacyState);for(const key of ['duration','appearance','player','events','home','away'])assert.deepEqual(plain(neutral[key]),plain(legacy[key]),key);assert.equal(JSON.stringify(s.player.stats),before);
 const raw=JSON.stringify(s.player.stats),selection=C.selection(DB,s);assert.equal(C.setPlayStyleBuild(DB,s,offensive),true);assert.equal(JSON.stringify(s.player.stats),raw);assert.equal(C.selection(DB,s),selection);const result=C.simulate(DB,fixture,s);assert.deepEqual(plain(result.playStyle.build),offensive);assert.ok(result.playStyle.opportunity.shotWeight>1);const frozen=JSON.stringify(result);assert.equal(C.setPlayStyleBuild(DB,s,defensive),true);assert.equal(JSON.stringify(result),frozen);assert.deepEqual(plain(C.simulate(DB,fixture,s).playStyle.build),defensive);
 const person={...s.player,id:'player'},neutralEffect=C.playStyleEffects(DB,C.playStyleDefaults(DB)),attack=C.playStyleEffects(DB,offensive),npc={...s.world.rosters[fixture.home][0]},base=C.effective(DB,person,'shooting',s,0,fixture,neutralEffect).skill,boost=C.effective(DB,person,'shooting',s,0,fixture,attack).skill;assert.ok(boost>base);assert.equal(C.effective(DB,npc,'shooting',s,0,fixture,neutralEffect).skill,C.effective(DB,npc,'shooting',s,0,fixture,attack).skill);
 s.matchPresentation={phase:'commentary'};assert.equal(C.setPlayStyleBuild(DB,s,offensive),false);
});

test('custom builds round-trip; old saves gain only neutral defaults and stock wording; broken references cannot mutate input',()=>{
 const s=career();assert.equal(C.setPlayStyleBuild(DB,s,offensive),true);const saved={schema:DB.meta.schema,db:C.clone(DB),state:s},before=JSON.stringify(saved),loaded=ctx.V.prepareImportedCareer(saved);assert.deepEqual(plain(loaded.state.player.playStyleBuild),offensive);assert.equal(JSON.stringify(saved),before);assert.equal(JSON.stringify(ctx.V.prepareImportedCareer(loaded)),JSON.stringify(loaded));
 const old=C.clone(saved);delete old.db.playStyleRules;delete old.state.player.playStyleBuild;old.db.meta.version='20.8.9';old.db.matchIntentRules.options.find(option=>option.id==='bold').name='과감한 판단을 시도한다';const oldState=JSON.stringify(old.state),upgraded=ctx.V.prepareImportedCareer(old),player={...upgraded.state.player};delete player.playStyleBuild;assert.deepEqual(plain(player),plain(old.state.player));assert.equal(JSON.stringify(upgraded.state.fixtures),JSON.stringify(old.state.fixtures));assert.equal(upgraded.state.date,old.state.date);assert.deepEqual(plain(upgraded.state.player.playStyleBuild),plain(C.playStyleDefaults(DB)));assert.equal(upgraded.db.matchIntentRules.options.find(option=>option.id==='bold').name,'과감한 플레이를 자주 시도한다');assert.equal(JSON.stringify(old.state),oldState);assert.ok(upgraded.state.player.history.every(record=>!record.result.playStyle));
 old.db.matchIntentRules.options.find(option=>option.id==='bold').name='사용자 지정 문구';assert.equal(ctx.V.prepareImportedCareer(old).db.matchIntentRules.options.find(option=>option.id==='bold').name,'사용자 지정 문구');
 for(const mutate of [value=>value.state.player.playStyleBuild.onBall='missing',value=>delete value.state.player.playStyleBuild.offBall,value=>value.db.playStyleRules.slots[0].options[0].load=1.1,value=>value.db.playStyleRules.slots[0].options[1].execution.shooting=Infinity]){const broken=C.clone(saved);mutate(broken);const snapshot=JSON.stringify(broken);assert.throws(()=>ctx.V.prepareImportedCareer(broken));assert.equal(JSON.stringify(broken),snapshot);}
});

function searchHarness(){
 const handlers={},inputs=Object.fromEntries(['world-search','world-club-search','agent-club-search'].map(id=>[id,{id,value:'',isConnected:true,selectionStart:0,selectionEnd:0}])),regions=Object.fromEntries(['data-world-search-rows','data-world-search-count'].flatMap(attribute=>['player','club'].map(kind=>[attribute+':'+kind,{innerHTML:''}])));
 const document={addEventListener:(event,fn)=>(handlers[event]??=[]).push(fn),querySelector:()=>({querySelector:selector=>{const m=selector.match(/\[(.+)="(.+)"\]/);return regions[m[1]+':'+m[2]];}}),createElement:()=>{const node={};Object.defineProperty(node,'innerHTML',{set:markup=>{const data=JSON.parse(markup);node.content={querySelectorAll:selector=>{const attribute=selector.slice(1,-1);return ['player','club'].map(kind=>({innerHTML:data[kind],getAttribute:()=>kind}));}};}});return node;}};
 const context=vm.createContext({document,WeakSet});const code=ui.slice(ui.indexOf('// Preserve the native input node'),ui.indexOf("document.addEventListener('change',event=>{if(event.target.closest('#profile-form'))",ui.indexOf('// Preserve the native input node')));
 vm.runInContext(`let worldQuery='',worldClubQuery='',agentClubQuery='',agentRefreshes=0;const refreshAgentTargets=()=>agentRefreshes++;const world=()=>JSON.stringify({player:worldQuery,club:worldClubQuery});const render=()=>{throw Error('Search replaced the input');};${code};globalThis.Q={queries:()=>({worldQuery,worldClubQuery,agentClubQuery}),agentRefreshes:()=>agentRefreshes};`,context);
 return {inputs,regions,Q:context.Q,dispatch:(event,input,isComposing=false)=>{for(const handler of handlers[event]||[])handler({target:input,isComposing});}};
}

test('Korean syllables compose continuously in all searches without replacing the native input, caret or committed query',()=>{
 for(const id of ['world-search','world-club-search','agent-club-search']){const harness=searchHarness(),input=harness.inputs[id],queryKey=id==='world-search'?'worldQuery':id==='world-club-search'?'worldClubQuery':'agentClubQuery';for(const [partial,completed] of [['ㅅ','서'],['서울ㅍ','서울파'],['서울파ㄹ','서울파리']]){harness.dispatch('compositionstart',input);input.value=partial;input.selectionStart=input.selectionEnd=partial.length;const committed=harness.Q.queries()[queryKey];harness.dispatch('input',input,false);assert.equal(harness.Q.queries()[queryKey],committed,'composition start protects even a missing isComposing flag');input.value=completed;input.selectionStart=input.selectionEnd=completed.length;harness.dispatch('compositionend',input);harness.dispatch('input',input,false);assert.equal(harness.Q.queries()[queryKey],completed);assert.strictEqual(harness.inputs[id],input);assert.equal(input.selectionStart,completed.length);assert.equal(input.selectionEnd,completed.length);}if(id==='agent-club-search')assert.equal(harness.Q.agentRefreshes(),3);else assert.equal(harness.regions['data-world-search-rows:'+(id==='world-search'?'player':'club')].innerHTML,'서울파리');input.value='';input.selectionStart=input.selectionEnd=0;harness.dispatch('input',input);assert.equal(harness.Q.queries()[queryKey],'');}
});

test('mixed text, mid-string edits, paste, clearing and detached composition endings preserve the expected search query',()=>{
 const h=searchHarness(),input=h.inputs['world-search'];input.value='서울 FC';input.selectionStart=input.selectionEnd=2;h.dispatch('input',input);assert.equal(h.Q.queries().worldQuery,'서울 FC');assert.equal(input.selectionStart,2);input.value='부산 서울 FC';h.dispatch('input',input,true);assert.equal(h.Q.queries().worldQuery,'서울 FC');h.dispatch('compositionend',input);assert.equal(h.Q.queries().worldQuery,'부산 서울 FC');input.isConnected=false;input.value='지연된 조합';h.dispatch('compositionend',input);assert.equal(h.Q.queries().worldQuery,'부산 서울 FC');
});
