const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ctx=vm.createContext({});
vm.runInContext(section('game-engine').replace(/return \{(?=[^}]*normalizeCareerSave)/,'return {generateRoster,')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,ui=section('game-ui');
const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast(')),imports=ui.slice(ui.indexOf('function prepareImportedCareer('),ui.indexOf('async function restoreCareer('));
vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=k=>k;${validators}${imports};globalThis.reload=prepareImportedCareer;`,ctx);
const create=()=>C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'화면 회귀 확인',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0');
test('training signs follow actual practice, survive seasons/saves and do not create stat penalties',()=>{
  const s=create(),practice=s.player.development.practice,start=s.date;
  assert.equal(C.trainingStatus(DB,s,'shooting'),'neutral');s.date=C.dateAdd(start,7);C.grow(DB,s,0,DB.training.find(t=>t.id==='shooting'));assert.equal(C.trainingStatus(DB,s,'shooting'),'positive');assert.equal(practice.last.shooting,s.date);assert.equal(practice.last.passing,undefined);
  const last=practice.last.shooting;s.date=C.dateAdd(start,14);s.player.injury=1;C.grow(DB,s,0,DB.training.find(t=>t.id==='passing'));assert.equal(practice.last.passing,undefined);s.player.injury=0;C.grow(DB,s,0,DB.training.find(t=>t.id==='rest'));assert.equal(practice.last.shooting,last);C.grow(DB,s,90,DB.training.find(t=>t.id==='passing'));assert.equal(practice.last.passing,undefined);
  s.date=C.dateAdd(start,28);const stats=JSON.stringify(s.player.stats);assert.equal(C.trainingStatus(DB,s,'passing'),'negative');assert.equal(C.trainingStatus(DB,s,'shooting'),'neutral');assert.equal(JSON.stringify(s.player.stats),stats);s.date=C.dateAdd(last,DB.trainingRules.stalePracticeDays);assert.equal(C.trainingStatus(DB,s,'shooting'),'negative');
  C.grow(DB,s,0,DB.training.find(t=>t.id==='balanced'));for(const a of DB.attributes)assert.equal(C.trainingStatus(DB,s,a.id),'positive');const saved=ctx.reload({schema:DB.meta.schema,db:DB,state:C.clone(s)});assert.equal(JSON.stringify(saved.state.player.development.practice),JSON.stringify(practice));
  for(const e of s.calendar.entries)e.completed=true;s.calendar.ended=true;assert.ok(C.nextSeason(DB,s));assert.equal(JSON.stringify(s.player.development.practice),JSON.stringify(practice));
});
test('expanded names avoid repeated components in new teams and take existing teammates into account',()=>{
  const s=create();for(const [country,first] of Object.entries(DB.names.firstNamesByCountry)){const last=DB.engine.lastNames[country],order=DB.names.nameOrders[country]||DB.names.nameOrders.default;assert.ok(first.length>=60);assert.ok(last.length>=59);assert.equal(first.length,new Set(first).size);assert.equal(last.length,new Set(last).size);
    const club=DB.clubs.find(c=>!c.historical&&C.clubCountry(DB,c)===country),team=s.world.rosters[club.id],parts=name=>{const family=last.slice().sort((a,b)=>b.length-a.length).find(x=>order.familyFirst?name.startsWith(x+order.separator):name.endsWith(order.separator+x));assert.ok(family,name);return [order.familyFirst?name.slice(family.length+order.separator.length):name.slice(0,-family.length-order.separator.length),family];};
    const components=team.map(p=>parts(p.name));for(const index of [0,1])assert.equal(new Set(components.map(x=>x[index])).size,team.length,country);
    const generated=C.generateRoster(DB,club.id,team),next=parts(generated[0].name);assert.ok(!team.some(p=>p.name===generated[0].name));for(const index of [0,1])assert.ok(!components.some(x=>x[index]===next[index]),country+' existing team component');
  }const names=Object.values(s.world.rosters).flat().map(p=>p.name);assert.equal(new Set(names).size,names.length);assert.ok(DB.worldConfig.managerNames.length>600);
});
test('schema 12 upgrade preserves fixtures, leaderboards, identities and contracts without inferring past practice',()=>{
  const s=create();while(!s.player.history.length)C.advance(DB,s);const peers=s.world.rosters[s.player.club];peers[1].name=peers[0].name;s.world.nameRegistry[peers[1].id]=peers[1].name;const oldDB=C.clone(DB);oldDB.meta.schema=12;oldDB.meta.version='13.0.0';oldDB.ui.tabs.push({id:'development',label:'성장 · 선수 DNA',icon:'↗'});delete oldDB.trainingRules.recentPracticeDays;delete oldDB.trainingRules.stalePracticeDays;s.schema=12;delete s.player.development.practice;
  const before=JSON.stringify(s),saved={schema:12,db:oldDB,state:s},upgraded=ctx.reload(saved);assert.equal(upgraded.schema,DB.meta.schema);for(const key of ['fixtures','competitionStats','calendar'])assert.equal(JSON.stringify(upgraded.state[key]),JSON.stringify(s[key]),key);for(const key of ['history','contract','stats'])assert.equal(JSON.stringify(upgraded.state.player[key]),JSON.stringify(s.player[key]),key);
  assert.equal(JSON.stringify(upgraded.state.world.rosters),JSON.stringify(s.world.rosters));assert.equal(upgraded.state.player.development.practice.since,s.date);assert.deepEqual(Object.keys(upgraded.state.player.development.practice.last),[]);assert.ok(!upgraded.db.ui.tabs.some(t=>t.id==='development'));assert.equal(JSON.stringify(s),before);
  const invalid=C.clone(upgraded);invalid.state.player.development.practice.last.shooting=C.dateAdd(s.date,1);assert.throws(()=>ctx.reload(invalid),/training.practice/);
});
test('Japanese name extensions are confined to Japanese nationality, including foreign players in Japan and retirees',()=>{
  const s=create(),jpClub=DB.clubs.find(c=>!c.historical&&C.clubCountry(DB,c)==='JP'),english=Object.values(s.world.rosters).flat().find(p=>p.country==='EN'),japanese=s.world.rosters[jpClub.id][0];assert.ok(DB.names.firstNamesByCountry.JP.length>=110);assert.ok(DB.engine.lastNames.JP.length>=110);
  const parse=(country,name)=>{const first=DB.names.firstNamesByCountry[country],last=DB.engine.lastNames[country],order=DB.names.nameOrders[country]||DB.names.nameOrders.default;return first.some(given=>last.some(family=>(order.familyFirst?[family,given]:[given,family]).join(order.separator)===name));};assert.ok(parse('JP',japanese.name));
  const origin=english.club;s.world.rosters[origin]=s.world.rosters[origin].filter(p=>p.id!==english.id);s.world.rosters[jpClub.id].push(english);english.club=jpClub.id;english.name='Foreign Player';delete s.world.nameRegistry[english.id];C.localizeWorld(DB,s,true);assert.equal(english.country,'EN');assert.ok(parse('EN',english.name));
  const retired={...C.clone(english),id:'foreign-retiree',name:'Retired Player',club:jpClub.id,country:'EN'};s.world.retired.push(retired);delete s.world.nameRegistry[retired.id];C.localizeWorld(DB,s);assert.ok(parse('EN',retired.name));assert.equal(retired.country,'EN');
});
