const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp(`<script id="${id}"[^>]*>([\\s\\S]*?)<\\/script>`))[1],DB=JSON.parse(section('game-db')),ctx=vm.createContext({});
vm.runInContext(section('game-engine').replace('return {rolePerformance,','return {reviewManager,replaceManager,rolePerformance,')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,ui=section('game-ui');
const validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast('));
vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)},Core=FootballCore,t=k=>k;${validators};globalThis.V={validateDB,validateSave};`,ctx);
const plain=x=>JSON.parse(JSON.stringify(x));
const create=()=>C.createCareer(DB,{...C.clone(DB.profile.defaults),name:'시즌 선택 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0');
const pending=(s,template)=>{const event=C.queueCareerDecision(DB,s);if(template)event.template=template;for(const e of s.calendar.entries)if(e.id!==event.id&&e.date<=event.date)e.completed=true;assert.equal(C.advance(DB,s).event.type,'decision');return event;};
test('every position receives between-game decisions, applies a choice once and persists it without instant stat growth',()=>{
  const original=create();for(const p of DB.positions){const s=C.clone(original);s.player.position=p.id;pending(s,'workload');const before=C.clone(s.player.stats),history=s.player.history.length;assert.equal(s.matchPresentation,undefined);assert.equal(s.careerStories.pending.template,'workload');const result=C.resolveCareerDecision(DB,s,'push');assert.ok(result);assert.equal(s.training,DB.roleProfiles.find(r=>r.position===p.id).focus);assert.deepEqual(plain(s.player.stats),plain(before));assert.equal(s.player.history.length,history);assert.equal(C.resolveCareerDecision(DB,s,'push'),false);assert.equal(s.careerStories.history.length,1);const loaded=C.normalizeCareerSave(DB,C.clone(s));ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:loaded});assert.equal(loaded.careerStories.history[0].option,'push');const next=loaded.calendar.entries.filter(e=>e.type==='decision'&&!e.completed);assert.equal(next.length,1);assert.ok(next[0].date>=C.dateAdd(s.date,DB.careerDecisionRules.intervalMinDays));assert.ok(next[0].date<=C.dateAdd(s.date,DB.careerDecisionRules.intervalMaxDays));}
});
test('pending decisions survive reload; temporary preparation affects actual match execution and expires',()=>{
  const s=create();pending(s,'tactics');const loaded=C.normalizeCareerSave(DB,C.clone(s));ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:loaded});assert.equal(loaded.careerStories.pending.id,s.careerStories.pending.id);C.resolveCareerDecision(DB,loaded,'study');const attr=loaded.careerStories.focus.attribute,person={...loaded.player,id:'player'},fixture=C.myFixtures(loaded).find(f=>!f.result),baseline=C.clone(loaded);baseline.careerStories.focus=null;assert.ok(C.effective(DB,person,attr,loaded,0,fixture).skill>C.effective(DB,person,attr,baseline,0,fixture).skill);loaded.player.trust=DB.rules.scale;loaded.player.fitness=DB.rules.scale;const report=C.simulate(DB,fixture,loaded);assert.equal(report.context.actions[attr].focus,DB.careerDecisionRules.focusMultiplier);loaded.date=C.dateAdd(loaded.careerStories.focus.until,1);assert.equal(C.effective(DB,person,attr,loaded,0,fixture).focus,1);const damaged=C.clone(s);damaged.careerStories.pending.template='missing';assert.throws(()=>ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:damaged}),/careerStories/);
});
test('calendar automation explicitly uses the neutral option; user choices never appear inside match simulation',()=>{
  const s=create();pending(s,'recovery');const id=s.careerStories.pending.id;C.advance(DB,s);const choice=s.careerStories.history.find(e=>e.id===id);assert.equal(choice.option,DB.careerDecisionRules.defaultOption);assert.equal(choice.automatic,true);const before=JSON.stringify(s.careerStories),f=C.myFixtures(s).find(f=>!f.result);C.simulate(DB,f,s);assert.equal(JSON.stringify(s.careerStories),before);
});
test('non-scoring positions have attainable role goals based only on their real statistics',()=>{
  for(const profile of DB.roleProfiles){const stats=C.createStats(DB);stats.minutes=DB.rules.matchMinutes;for(const m of profile.metrics){if(m.field==='passAccuracy'){stats.passes=100;stats.completed=m.target;}else stats[m.field]=m.target;}const before=JSON.stringify(stats),role=C.rolePerformance(DB,stats,profile.position);assert.equal(role.achieved,true);assert.equal(role.score,DB.rolePerformanceRules.scoreScale);assert.equal(JSON.stringify(stats),before);stats.minutes=DB.rolePerformanceRules.minimumMinutes-1;assert.equal(C.rolePerformance(DB,stats,profile.position).achieved,false);}
});
test('manager changes require a long tenure and persistent poor results, with one change per season',()=>{
  const s=create(),club=s.player.club,league=C.indexes(DB,s).clubs[club].league,m=s.world.clubs[club].manager,first=m.id;
  for(const f of s.fixtures[league])if(f.home===club||f.away===club)f.result={home:{stats:{goals:f.home===club?0:3}},away:{stats:{goals:f.away===club?0:3}}};
  s.date=C.dateAdd(s.seasonStart,DB.managerRules.minimumTenureDays-1);C.reviewManager(DB,s,club,()=>.02);assert.equal(s.world.clubs[club].manager.id,first);
  s.date=C.dateAdd(s.seasonStart,DB.managerRules.minimumTenureDays);C.reviewManager(DB,s,club,()=>.02);assert.equal(s.world.clubs[club].manager.id,first);s.date=C.dateAdd(s.date,DB.managerRules.reviewIntervalDays);C.reviewManager(DB,s,club,()=>.02);assert.notEqual(s.world.clubs[club].manager.id,first);const replacement=s.world.clubs[club].manager;replacement.appointmentDate=s.seasonStart;replacement.lastReviewDate=s.seasonStart;replacement.poorReviews=DB.managerRules.poorReviewsRequired;s.date=C.dateAdd(s.date,DB.managerRules.reviewIntervalDays);C.reviewManager(DB,s,club,()=>0);assert.equal(s.world.clubs[club].manager.id,replacement.id);
});
test('negotiations keep their full lifetime across registration deadlines and existing live saves get time to finish',()=>{
  const s=create();for(const a of DB.attributes)s.player.stats[a.id]=DB.careerPolishRules.previousInitialAttributes[a.id];s.player.freeAgent=true;const target=DB.clubs.find(c=>!c.parent&&!c.historical&&c.id!==s.player.club&&c.league==='kr-2');assert.ok(C.seekClub(DB,s,target.id));for(let i=0;i<30&&!s.offers.some(o=>o.club===target.id);i++)C.advance(DB,s);const d=C.startDeal(DB,s,target.id);assert.ok(d);assert.equal(d.deadline,C.dateAdd(s.date,DB.dealRules.expiryDays));s.player.freeAgent=false;d.terms.arrival='nearest';const end=s.calendar.entries.find(e=>e.type==='deadline');s.date=C.dateAdd(end.date,-1);d.plannedArrival=s.date;d.createdDate=C.dateAdd(s.date,-5);d.deadline=C.dateAdd(d.createdDate,DB.dealRules.expiryDays);for(const e of s.calendar.entries)e.completed=e.id!==end.id;C.advance(DB,s);assert.equal(d.status,'negotiating');assert.ok(d.plannedArrival>end.date);assert.equal(d.deadline,C.dateAdd(d.createdDate,DB.dealRules.expiryDays));delete d.timingRevision;d.deadline=C.dateAdd(s.date,1);C.normalizeCareerSave(DB,s);assert.equal(d.deadline,C.dateAdd(d.createdDate,DB.dealRules.expiryDays));
});
test('season review freezes all league tables and leaders before promotion, and retains personal records and decisions',()=>{
  const s=create();pending(s,'teamwork');C.resolveCareerDecision(DB,s,'connect');while(!s.player.history.length)C.advance(DB,s);const league=C.indexes(DB,s).clubs[s.player.club].league;for(const f of s.fixtures[league])if(!f.result)f.result={home:{stats:{goals:0}},away:{stats:{goals:0}}};assert.equal(C.seasonReviewReady(DB,s),false);assert.equal(C.captureSeasonReview(DB,s),null);for(const [id,list] of Object.entries(s.fixtures))for(const f of list)if(!f.result)f.result={home:{stats:{goals:0}},away:{stats:{goals:0}}};
  C.advancePostseason(DB,s);for(let pass=0;pass<30&&Object.values(s.postseason.competitions).some(t=>t.status!=='complete');pass++){for(const t of Object.values(s.postseason.competitions))for(const f of s.fixtures[t.competition]||[])if(!f.result){f.result={duration:90,home:{stats:{goals:0}},away:{stats:{goals:0}}};C.resolvePlayoffResult(DB,s,f,f.result);C.advanceTrainingDays(DB,s,[s.date,f.date].sort().at(-1),false);}C.advancePostseason(DB,s);}
  for(const e of s.calendar.entries)e.completed=true;s.calendar.ended=true;assert.equal(C.seasonReviewReady(DB,s),true);const review=C.captureSeasonReview(DB,s);assert.equal(review.final,true);assert.equal(review.choices.length,s.careerStories.history.length);assert.deepEqual(plain(review.stats),plain(C.totals(DB,s.player.history)));assert.equal(review.leagues.length,DB.leagues.filter(l=>!['continental','postseason'].includes(l.kind)).length);assert.deepEqual(plain(review.leagues.find(l=>l.id===league).goals),plain(C.leaders(DB,s,league,'goals').slice(0,DB.seasonReviewRules.leaderLimit)));ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});const snapshot=JSON.stringify(review.leagues);s.fixtures[league][0].result.home.stats.goals=9;assert.equal(JSON.stringify(review.leagues),snapshot);assert.equal(C.nextSeason(DB,s),true);assert.equal(s.seasonRecaps[0].final,true);assert.equal(s.seasonRecaps[0].season,1);assert.equal(s.seasonBaseline.season,2);ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:s});
});
