const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),section=id=>html.match(new RegExp('<script id="'+id+'"[^>]*>([\\s\\S]*?)<\\/script>'))[1],DB=JSON.parse(section('game-db')),ui=section('game-ui'),ctx=vm.createContext({});new vm.Script(ui);vm.runInContext(section('game-engine')+';globalThis.C=FootballCore;',ctx);const C=ctx.C,clone=C.clone,plain=v=>JSON.parse(JSON.stringify(v));
const base=C.createCareer(DB,{...clone(DB.profile.defaults),name:'특성 계기 검증',stats:Object.fromEntries(DB.attributes.map(a=>[a.id,a.initial]))},'domestic','kr2-0'),validators=ui.slice(ui.indexOf('function validateDB('),ui.indexOf('function toast(')),imports=ui.slice(ui.indexOf('function prepareImportedCareer('),ui.indexOf('async function restoreCareer('));vm.runInContext(`const DEFAULT_DB=${JSON.stringify(DB)};const Core=FootballCore;const t=key=>key;${validators}${imports};globalThis.V={validateDB,validateSave,prepareImportedCareer};`,ctx);
function annual(){const s=clone(base);s.date=s.player.traitProgress.nextReviewDate;s.player.traitProgress.activeDays=200;s.player.traitProgress.trainingDays=80;s.trainingProgram.reviewDate=C.dateAdd(s.date,DB.trainingProgramRules.blockDays);return s;}
function matches(s,values){for(let i=0;i<4;i++){const stats=C.createStats(DB);Object.assign(stats,{minutes:90,rating:7,...(i===0?values:{})});s.player.history.push({date:C.dateAdd(s.date,-40+i*7),club:s.player.club,appearance:'starter',stats});}}
test('no trait is granted without explicit qualifying evidence, regardless of seed',()=>{
 for(const seed of [1,2,80,999]){const s=annual();s.seed=seed;assert.equal(C.reviewCareerTraits(DB,s).length,0);assert.equal(s.player.careerTraits.length,0);assert.equal(C.reviewCareerTraits(DB,s).length,0);}
 const active=annual();active.player.traitProgress.activeDays=0;active.player.traitProgress.trainingDays=0;assert.equal(C.reviewCareerTraits(DB,active).length,0);
});
test('goals, assists and disciplinary conduct grant their own traits with actual immutable reasons',()=>{
 for(const [id,values,needle] of [['finisher',{goals:10,shots:50},'10골'],['creator',{assists:8,keyPasses:40},'도움 8개'],['hothead',{yellow:10,fouls:30},'반칙 30회']]){const s=annual();matches(s,values);const result=C.reviewCareerTraits(DB,s);assert.deepEqual(plain(result.map(e=>e.id)),[id]);assert.ok(result[0].reason.includes(needle));assert.ok(s.inbox.at(-1).body.includes(result[0].reason));const reason=result[0].reason;s.player.history[0].stats.goals=999;assert.equal(result[0].reason,reason);assert.equal(C.reviewCareerTraits(DB,s).length,0);}
 const insufficient=annual();matches(insufficient,{goals:9,shots:50});assert.equal(C.reviewCareerTraits(DB,insufficient).length,0);
});
test('training absence excludes long injuries and skill traits require relevant successful actions',()=>{
 const s=annual();s.player.traitProgress.trainingDays=0;s.player.development.injuries=[{date:C.dateAdd(s.date,-170),weeks:20,injury:'major',loss:0,season:1,style:s.player.development.style}];const lazy=DB.careerTraitRules.traits.find(t=>t.id==='lazy');assert.equal(C.careerTraitQualification(DB,s,lazy),null);
 const dribbler=annual();matches(dribbler,{dribbles:100,dribblesWon:80});const facts=C.careerTraitFacts(DB,dribbler);assert.ok(C.careerTraitQualification(DB,dribbler,DB.careerTraitRules.traits.find(t=>t.id==='artist'),facts));assert.equal(C.careerTraitQualification(DB,dribbler,DB.careerTraitRules.traits.find(t=>t.id==='winner'),facts),null);
 const trained=annual();trained.player.traitProgress.trainingDays=150;assert.ok(C.reviewCareerTraits(DB,trained).some(e=>e.id==='diligent'));
});
test('all trait definitions have enforceable conditions and old saves retain earned traits without fabricated reasons',()=>{
 assert.equal(Object.keys(DB.careerTraitRules.acquisitionRules).length,DB.careerTraitRules.traits.length);const s=annual();matches(s,{goals:10,shots:50});C.reviewCareerTraits(DB,s);s.player.history=[];const loaded=ctx.V.prepareImportedCareer({schema:DB.meta.schema,db:clone(DB),state:s});assert.deepEqual(plain(loaded.state.player.careerTraits),plain(s.player.careerTraits));
 const old=clone(DB);delete old.careerTraitRules.acquisitionRules;delete old.careerTraitRules.reasonDigits;old.ui.labels.careerTraitsHint=DB.careerTraitRules.previousHint;old.ui.labels.traitAcquiredBody=DB.careerTraitRules.previousMail;const legacy=clone(base);legacy.player.careerTraits=[{id:'artist',date:legacy.date,season:1,evidence:'appearances'}];const restored=ctx.V.prepareImportedCareer({schema:DB.meta.schema,db:old,state:legacy});assert.equal(restored.state.player.careerTraits[0].reason,undefined);assert.equal(restored.db.ui.labels.careerTraitsHint,DB.ui.labels.careerTraitsHint);
 const bad=clone(DB);bad.careerTraitRules.acquisitionRules.finisher.conditions[0].metric='unknown';assert.throws(()=>ctx.V.validateDB(bad),/acquisition/);const broken=clone(s);broken.player.careerTraits[0].cause.metrics.goals=-1;assert.throws(()=>ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:broken}),/careerIdentity/);
});
test('Puma rewards increase fivefold while custom values and signed contracts remain unchanged',()=>{
 const puma=DB.economyRules.commercial.find(x=>x.id==='local-boots');assert.equal(puma.upfront,2000);assert.equal(puma.payment,750);assert.equal(puma.goalBonus,75);const old=clone(DB),product=old.economyRules.commercial.find(x=>x.id===puma.id);Object.assign(product,DB.economyRules.pumaRewardUpgrade);C.upgradeDatabase(DB,old);assert.equal(product.payment,750);product.payment=1234;C.upgradeDatabase(DB,old);assert.equal(product.payment,1234);
 const s=clone(base);assert.ok(C.signCommercial(DB,s,puma.id,DB.economyRules.packages[0].id));const contracts=JSON.stringify(s.economy.contracts);C.upgradeDatabase(DB,old);assert.equal(JSON.stringify(s.economy.contracts),contracts);
});
test('intensive training has a rare reproducible injury risk, while rest, ordinary training and rehab cannot trigger it',()=>{
 const s=clone(base);s.trainingProgram.plan.intensity='intensive';const session={work:true,kind:'primary',load:5};assert.equal(C.trainingInjuryChance(DB,s,session),.0002);s.trainingProgram.fatigue=100;assert.equal(C.trainingInjuryChance(DB,s,session),.0004);s.trainingProgram.plan.intensity='standard';assert.equal(C.trainingInjuryChance(DB,s,session),0);s.trainingProgram.plan.intensity='intensive';assert.equal(C.trainingInjuryChance(DB,s,{...session,work:false}),0);
 const forced=clone(DB);forced.trainingProgramRules.injuryRisk.dailyChance.intensive=1;forced.trainingProgramRules.injuryRisk.maximumChance=1;const p=clone(base);p.trainingProgram.plan.intensity='intensive';const stats=JSON.stringify(p.player.stats);assert.equal(C.trainingInjury(forced,p,session),'strain');assert.equal(p.player.injuryDays,14);assert.equal(p.player.development.injuries.at(-1).source,'training');assert.ok(p.inbox.at(-1).body.includes('훈련 중'));assert.equal(JSON.stringify(p.player.stats),stats);assert.equal(C.trainingInjury(forced,p,session),null);assert.equal(C.trainingSession(DB,p).kind,'rehab');ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:p});
 const q=clone(base);q.trainingProgram.plan.intensity='intensive';q.training=q.trainingProgram.plan.primary;const next=C.dateAdd(q.date,1);assert.ok(!C.myFixtures(q).some(f=>f.date===next));C.advanceTrainingDays(forced,q,next,false);assert.equal(q.player.development.injuries.at(-1).source,'training');assert.ok(q.trainingProgram.sessions.at(-1).injury);ctx.V.validateSave({schema:DB.meta.schema,db:DB,state:q});
});
test('requested UI removes extra labels, lists latest values first and puts club information at the right of filters',()=>{
 const chart=ui.slice(ui.indexOf('function playerValueHistoryCard(){'),ui.indexOf('function career(){'));assert.ok(!chart.includes("t('valueHistoryHint')"));assert.ok(chart.includes('records.slice().reverse().map(record=>'));
 const card=ui.slice(ui.indexOf('function careerTraitsCard(){'),ui.indexOf('function moneyInputNumber('));assert.ok(!card.includes('traitPositive'));assert.ok(!card.includes('traitNegative'));assert.ok(card.includes('e.reason'));
 const filters=ui.slice(ui.indexOf('function teamBrowseControls('),ui.indexOf('\n',ui.indexOf('function teamBrowseControls(')));assert.ok(filters.includes('team-browse-tools'));assert.ok(filters.indexOf("t('browseClubDetails')")>filters.indexOf('team-browse-club'));assert.ok(html.includes('.team-browse-tools>button{margin-left:auto;'));
});
